"""Custom Pygments styles for Litestar Queues documentation."""

from pygments.style import Style
from pygments.token import (
    Comment,
    Error,
    Generic,
    Keyword,
    Name,
    Number,
    Operator,
    Punctuation,
    String,
    Token,
    Whitespace,
)


class LitestarQueuesLightStyle(Style):
    """Light syntax highlighting style for Litestar Queues documentation."""

    name = "litestar-queues-light"
    background_color = "#f1f4f9"

    styles = {
        Token: "#202235",
        Whitespace: "",
        Error: "#dc2626",
        Keyword: "bold #7c3aed",
        Keyword.Constant: "bold #7c3aed",
        Keyword.Declaration: "bold #7c3aed",
        Keyword.Namespace: "bold #7c3aed",
        Keyword.Pseudo: "bold #7c3aed",
        Keyword.Reserved: "bold #7c3aed",
        Keyword.Type: "bold #6d28d9",
        Name: "#202235",
        Name.Attribute: "#8b6914",
        Name.Builtin: "#0369a1",
        Name.Builtin.Pseudo: "#0369a1",
        Name.Class: "#c2410c",
        Name.Constant: "#202235",
        Name.Decorator: "italic #c2410c",
        Name.Entity: "#202235",
        Name.Exception: "#b91c1c",
        Name.Function: "#c2410c",
        Name.Function.Magic: "#c2410c",
        Name.Label: "#202235",
        Name.Namespace: "#0e7490",
        Name.Other: "#202235",
        Name.Property: "#202235",
        Name.Tag: "#202235",
        Name.Variable: "#202235",
        Name.Variable.Class: "#202235",
        Name.Variable.Global: "#202235",
        Name.Variable.Instance: "#202235",
        Name.Variable.Magic: "#202235",
        String: "#107535",
        String.Affix: "#107535",
        String.Backtick: "#107535",
        String.Char: "#107535",
        String.Delimiter: "#107535",
        String.Doc: "italic #4d7c0f",
        String.Double: "#107535",
        String.Escape: "bold #0d6d6e",
        String.Heredoc: "#107535",
        String.Interpol: "#0d6d6e",
        String.Other: "#107535",
        String.Regex: "#107535",
        String.Single: "#107535",
        String.Symbol: "#107535",
        Number: "#b45309",
        Comment: "italic #6b7280",
        Comment.Hashbang: "italic #6b7280",
        Comment.Multiline: "italic #6b7280",
        Comment.Preproc: "italic #6b7280",
        Comment.PreprocFile: "italic #6b7280",
        Comment.Single: "italic #6b7280",
        Comment.Special: "italic #6b7280",
        Operator: "#64748b",
        Operator.Word: "bold #7c3aed",
        Punctuation: "#475569",
        Generic.Deleted: "#dc2626",
        Generic.Emph: "italic",
        Generic.Error: "#dc2626",
        Generic.Heading: "bold",
        Generic.Inserted: "#107535",
        Generic.Output: "",
        Generic.Prompt: "bold",
        Generic.Strong: "bold",
        Generic.Subheading: "bold",
        Generic.Traceback: "#dc2626",
    }


class LitestarQueuesDarkStyle(Style):
    """Dark syntax highlighting style for Litestar Queues documentation."""

    name = "litestar-queues-dark"
    background_color = "#1a1c2e"

    styles = {
        Token: "#e6edf3",
        Whitespace: "",
        Error: "#ef9a9a",
        Keyword: "bold #cba6f7",
        Keyword.Constant: "bold #cba6f7",
        Keyword.Declaration: "bold #cba6f7",
        Keyword.Namespace: "bold #cba6f7",
        Keyword.Pseudo: "bold #cba6f7",
        Keyword.Reserved: "bold #cba6f7",
        Keyword.Type: "bold #b4befe",
        Name: "#cdd6f4",
        Name.Attribute: "#f9e2af",
        Name.Builtin: "#89dceb",
        Name.Builtin.Pseudo: "#89dceb",
        Name.Class: "#fab387",
        Name.Constant: "#cdd6f4",
        Name.Decorator: "italic #fab387",
        Name.Entity: "#cdd6f4",
        Name.Exception: "#ef9a9a",
        Name.Function: "#fab387",
        Name.Function.Magic: "#fab387",
        Name.Label: "#cdd6f4",
        Name.Namespace: "#94e2d5",
        Name.Other: "#cdd6f4",
        Name.Property: "#cdd6f4",
        Name.Tag: "#cdd6f4",
        Name.Variable: "#e6edf3",
        Name.Variable.Class: "#e6edf3",
        Name.Variable.Global: "#e6edf3",
        Name.Variable.Instance: "#e6edf3",
        Name.Variable.Magic: "#e6edf3",
        String: "#a5d6a7",
        String.Affix: "#a5d6a7",
        String.Backtick: "#a5d6a7",
        String.Char: "#a5d6a7",
        String.Delimiter: "#a5d6a7",
        String.Doc: "italic #a6e3a1",
        String.Double: "#a5d6a7",
        String.Escape: "bold #94e2d5",
        String.Heredoc: "#a5d6a7",
        String.Interpol: "#94e2d5",
        String.Other: "#a5d6a7",
        String.Regex: "#a5d6a7",
        String.Single: "#a5d6a7",
        String.Symbol: "#a5d6a7",
        Number: "#fab387",
        Comment: "italic #9ca3af",
        Comment.Hashbang: "italic #9ca3af",
        Comment.Multiline: "italic #9ca3af",
        Comment.Preproc: "italic #9ca3af",
        Comment.PreprocFile: "italic #9ca3af",
        Comment.Single: "italic #9ca3af",
        Comment.Special: "italic #9ca3af",
        Operator: "#b0bec5",
        Operator.Word: "bold #cba6f7",
        Punctuation: "#9ca3af",
        Generic.Deleted: "#ef9a9a",
        Generic.Emph: "italic",
        Generic.Error: "#ef9a9a",
        Generic.Heading: "bold",
        Generic.Inserted: "#a5d6a7",
        Generic.Output: "",
        Generic.Prompt: "bold",
        Generic.Strong: "bold",
        Generic.Subheading: "bold",
        Generic.Traceback: "#ef9a9a",
    }
