from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping, Sequence


class KafkaProducer(Protocol):
    async def start(self) -> "None": ...

    async def stop(self) -> "None": ...

    async def send_and_wait(
        self, topic: "str", value: "bytes", *, headers: "Sequence[tuple[str, bytes]]"
    ) -> "object": ...


class KafkaConsumer(Protocol):
    def subscribe(self, topics: "Iterable[str]", listener: "Any") -> "None": ...

    def assignment(self) -> "set[Any]": ...

    async def start(self) -> "None": ...

    async def stop(self) -> "None": ...

    async def getmany(self, *, timeout_ms: "int", max_records: "int") -> "Mapping[Any, list[Any]]": ...

    async def commit(self, offsets: "Mapping[Any, int]") -> "None": ...
