"""Internal Redis-protocol client typing helpers."""

from collections.abc import Set as AbstractSet
from typing import Any, Protocol


class RedisPipelineLike(Protocol):
    """Pipeline subset used by the Redis queue backend."""

    def delete(self, *keys: str) -> object: ...

    def eval(self, script: str, numkeys: int, *keys_and_args: str) -> object: ...

    def hgetall(self, key: str) -> object: ...

    def hset(
        self, name: str, key: str | None = None, value: Any | None = None, *, mapping: dict[str, str] | None = None
    ) -> object: ...

    def sadd(self, name: str, *values: str) -> object: ...

    def scard(self, key: str) -> object: ...

    def smembers(self, key: str) -> object: ...

    def srem(self, name: str, *values: str) -> object: ...

    def zadd(self, name: str, mapping: dict[str, float]) -> object: ...

    def zrem(self, name: str, *values: str) -> object: ...

    def execute(self) -> object: ...


class RedisPubSubLike(Protocol):
    """PubSub subset used by the Redis queue backend."""

    def subscribe(self, channel: str) -> object: ...

    async def get_message(self, *, ignore_subscribe_messages: bool, timeout: float | None) -> Any: ...

    def unsubscribe(self, channel: str) -> object: ...


class RedisClientLike(Protocol):
    """Async Redis-protocol client subset used by the queue backend."""

    def pubsub(self) -> RedisPubSubLike: ...

    def pipeline(self, *, transaction: bool = False) -> RedisPipelineLike: ...

    async def delete(self, *keys: str) -> Any: ...

    def eval(self, script: str, numkeys: int, *keys_and_args: str) -> Any: ...

    async def get(self, name: str) -> Any: ...

    async def hdel(self, name: str, key: str) -> Any: ...

    async def hget(self, name: str, key: str) -> Any: ...

    async def hgetall(self, name: str) -> dict[Any, Any]: ...

    async def hset(
        self, name: str, key: str | None = None, value: Any | None = None, *, mapping: dict[str, str] | None = None
    ) -> Any: ...

    async def publish(self, channel: str, message: str) -> Any: ...

    async def sadd(self, name: str, *values: str) -> Any: ...

    async def scard(self, name: str) -> Any: ...

    async def set(self, name: str, value: str, *, nx: bool = False, px: int | None = None) -> Any: ...

    async def smembers(self, name: str) -> AbstractSet[Any]: ...

    async def srem(self, name: str, *values: str) -> Any: ...

    async def zadd(self, name: str, mapping: dict[str, float]) -> Any: ...

    async def zrange(self, name: str, start: int, end: int) -> list[Any]: ...

    async def zrangebyscore(
        self, name: str, minimum: float | str, maximum: float | str, *, start: int | None = None, num: int | None = None
    ) -> list[Any]: ...

    async def zrem(self, name: str, *values: str) -> Any: ...
