name: Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      coverage:
        required: false
        type: boolean
        default: false
      os:
        required: false
        type: string
        default: "ubuntu-latest"
      timeout:
        required: false
        type: number
        default: 60

jobs:
  test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install ${{ inputs.python-version }}

      - name: Install dependencies
        env:
          UV_PYTHON: ${{ inputs.python-version }}
        run: make install-test-adapters

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src" >> $GITHUB_ENV

      - name: Test
        if: ${{ !inputs.coverage }}
        env:
          UV_PYTHON: ${{ inputs.python-version }}
        run: uv run pytest src/tests -n 2

      - name: Test with coverage
        if: ${{ inputs.coverage }}
        env:
          UV_PYTHON: ${{ inputs.python-version }}
        run: uv run pytest src/tests --cov=litestar_queues --cov-report=xml -n 2

      - uses: actions/upload-artifact@v7
        if: ${{ inputs.coverage }}
        with:
          name: coverage-xml
          path: coverage.xml
